name: Update Single Page

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update:
    name: Update Single Page
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Configure Git
        run: |
          git config user.name "taskylizard"
          git config user.email "75871323+taskylizard@users.noreply.github.com"

      - name: Update
        shell: bash
        run: |
          python .github/single-page.py
          git add .
          git commit -m '♻️ update single page'
          git push
